Implement several DeviceService ONVIF functions
atagirov/onvif4go pull request #6
Opened 2019-07-31 18:22 UTC by jdharms

Followed existing pattern and implemented most of the simple "get"
functions in the Device Servie.

Signed-off-by: Daniel Harms <jdharms@gmail.com>

2019-08-06 12:11 UTC, atagirov requested changes

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +func (s *DeviceService) SetSystemDateAndTime(datetime time.Time, datetimeType string, dst bool, timezone string) (err error) {
SetSystemDateAndTime can use by two way: Manual and NTP.

When we use NTP - datetime params is not required. It can confuse.

I have 2 solutions for this: 
* make 2 methods: **SetSystemDateAndTimeManual** and **SetSystemDateAndTimeByNTP**. Method names must started from SetSystemDateAndTime (if I found describe of this method in ONVIF documentations I will looking for it in the library by same name)
* accept tds.SetSystemDateAndTime as parameter for this method. Additionaly we will add 2 methods in tds module for make SetSystemDateAndTime for both cases (**NewManualSetSystemDateAndTime** and **NewNTPSetSystemDateAndTime** for example)

```golang
err := device.SetSystemDateAndTimeNTP(ds, timezone)
err := device.SetSystemDateAndTimeManual(datetime, ds, timezone)

err := device.SetSystemDateAndTime(tds.NewNTPSetSystemDateAndTime(ds, timezone))
err := device.SetSystemDateAndTime(tds.NewManualSetSystemDateAndTime(datetime, ds, timezone))
```

What do you think about this?

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +		TimeZone: tt.TimeZone{TZ: xsd.Token(timezone)},
time.Time can contains information about DTS and TimeZone, but is hard for convert it to POSIX 1003.1 format.

Other variant. We always must convert incoming datetime to UTC.

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +	err = s.Client.Call(tds.SetSystemDateAndTime{
tds.SetSystemDateAndTime described with error currently: TimeZone and UTCDateTime can be ommit.

It will be perfect if you change this

device/types.go
```golang
type SetSystemDateAndTime struct {
	XMLName         string                 `xml:"http://www.onvif.org/ver10/device/wsdl SetSystemDateAndTime"`
	DateTimeType    onvif.SetDateTimeType  `xml:"http://www.onvif.org/ver10/device/wsdl DateTimeType"`
	DaylightSavings bool                   `xml:"http://www.onvif.org/ver10/device/wsdl DaylightSavings"`
	TimeZone        *onvif.TimeZone        `xml:"http://www.onvif.org/ver10/device/wsdl TimeZone"`
	UTCDateTime     *onvif.DateTime        `xml:"http://www.onvif.org/ver10/device/wsdl UTCDateTime"`
}
```

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +func (s *DeviceService) SetRemoteUser(username string, password string, useDerivedPassword bool) (err error) {
> To remove the remote user SetRemoteUser should be called without the RemoteUser parameter

We must add method RemoveRemoteUser or accept *tt.RemoteUser as parameter.

I like variant with accept tt.RemoteUser as parameter. It also allow get tt.RemoteUser from **GetRemoteUser**, change some fields and send as parameter to this method.

```golang

res, err := device.GetRemoteUser()
if (err != nil) {
  ...
}
if (res.RemoteUser == nil) {
  ...
}
remoteUser := res.RemoteUser
remoteUser.Password = "new strong password"

err = device.SetRemoteUser(remoteUser)
```

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +func (s *DeviceService) SetRemoteUser(username string, password string, useDerivedPassword bool) (err error) {
I found your **RemoveRemoteUser** method :)

But i think, that tt.RemoteUser as parameter is better. What do you think?

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +func (s *DeviceService) CreateUsers() (err error) {
To leave commented wsdl:operation is better.

2019-08-06 12:11 UTC, atagirov commented on deviceService.go
> +func (s *DeviceService) CreateUser(username, password, userlevel, extension string) (err error) {
What do you think about 
```golang
func (s *DeviceService) CreateUser(users ...tt.User) (err error) {
  ...
}
```

We also can hide logic with UserExtension in 
```golang
user := tt.NewUser(username, password, userlevel, extension)
```

Additionaly we can reuse `user` object in SetUser

2019-08-06 12:24 UTC, atagirov commented on deviceService.go
> +func (s *DeviceService) CreateUser(username, password, userlevel, extension string) (err error) {
We can ommit extension for first time:

```golang
func NewUser(username, password, level string) *User {
	return User{
		Username: username,
		Password: password,
		UserLevel: UserLevel(level),
	}
}
```

If user needs extension, they can write:
```golang
user := tt.NewUser("admin", "password", "admin")
user.Extention = tt.UserExtension("extension")
...
```

But i don't know some use cases for this

2019-08-06 14:15 UTC, jdharms commented on deviceService.go
> +func (s *DeviceService) SetSystemDateAndTime(datetime time.Time, datetimeType string, dst bool, timezone string) (err error) {
I think the first solution is probably better, but I could be convinced of either.  So far I hadn't made any of the ONVIF Get/Set structs as arguments to the API functions (just responses).

I don't know if that is important or not. Do you think for some functions we will be required (or should) take the request struct as the parameter?

2019-08-06 14:44 UTC, jdharms commented on deviceService.go
> +		TimeZone: tt.TimeZone{TZ: xsd.Token(timezone)},
I hadn't realized the TimeZone must be posix format.  You are right--converting looks very hard.

If we always convert to UTC then the Daylight Savings option will not work.

What are your thoughts on this issue?

2019-08-06 14:44 UTC, jdharms commented on deviceService.go
> +	err = s.Client.Call(tds.SetSystemDateAndTime{
That makes sense, I will make this change.

2019-08-06 14:46 UTC, jdharms commented on deviceService.go
> +func (s *DeviceService) SetRemoteUser(username string, password string, useDerivedPassword bool) (err error) {
>It also allow get tt.RemoteUser from GetRemoteUser, change some fields and send as parameter to this method.

I hadn't written any methods to accept the library's structures as arguments, but this is a compelling reason to do so.  I think you are right--I will rewrite my methods.

2019-08-06 14:46 UTC, jdharms commented on deviceService.go
> +func (s *DeviceService) CreateUsers() (err error) {
Agreed.  I will change this back.

2019-08-06 15:11 UTC, jdharms commented on deviceService.go
> +func (s *DeviceService) CreateUser(username, password, userlevel, extension string) (err error) {
I like this solution.

2019-08-06 15:12 UTC, jdharms commented on deviceService.go
> +func (s *DeviceService) SetSystemDateAndTime(datetime time.Time, datetimeType string, dst bool, timezone string) (err error) {
After reading through the rest of your feedback I now think the second option is the better one! :)

2019-08-06 19:04 UTC, jdharms commented on deviceService.go
> +		TimeZone: tt.TimeZone{TZ: xsd.Token(timezone)},
The DaylightSavings flag isn't to indicate that the current time is DST or not, but whether or not the DST information inside the TZ string should be used or not.

>The DayLightSavings flag should be set to true to activate any DST settings of the TimeZone string. Clear the DayLightSavings flag if the DST portion of the TimeZone settings should be ignored.

So we have to take DST as a parameter no matter what.

2019-08-06 19:52 UTC, jdharms commented
Updated pull request to address feedback

2019-08-07 06:00 UTC, atagirov commented on .gitignore
> +go.sum
it's don't matter for this library now, but i should insert this link:

https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

I'll change this later

2019-08-07 06:01 UTC, merged